addReviewers: true

addAssignees: author

# Set this to the length of the reviewers list
# because the default was not including everyone
numberOfReviewers: 3

reviewers:
  - prateekpandey14
  - sonasingh46
  - mittachaitu
  - shubham14bajpai

skipKeywords:
  - wip
