apiVersion: cstor.openebs.io/v1
kind: CStorPoolCluster
metadata:
  name: cspc-stripe
  namespace: openebs
spec:
  pools:
    - nodeSelector:
        kubernetes.io/hostname: "127.0.0.1"
      dataRaidGroups:
        - blockDevices:
            - blockDeviceName: "sparse-177b6bc2ae2dd332c7a384a02179368b"
      poolConfig:
        dataRaidGroupType: "stripe"
