apiVersion: cstor.openebs.io/v1
kind: CStorPoolCluster
metadata:
  name: sparse-claim
  namespace: openebs
spec:
  pools:
    - nodeSelector:
        kubernetes.io/hostname: "127.0.0.1"
      dataRaidGroups:
      - blockDevices:
          - blockDeviceName: "sparse-37a7de580322f43a13338bf2467343f5"
      poolConfig:
        dataRaidGroupType: "stripe"
