apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ template "openebs-cstor.fullname" . }}-cvc-operator
  {{- if .Values.cvcOperator.annotations }}
  annotations:
  {{ toYaml .Values.cvcOperator.annotations | indent 4 }}
  {{- end }}
  labels:
    {{- include "openebs-cstor.cvcOperator.labels" . | nindent 4 }}
spec:
  selector:
    matchLabels:
      {{- include "openebs-cstor.cvcOperator.matchLabels" . | nindent 6 }}
  replicas: {{ .Values.cvcOperator.replicas }}
  strategy:
    type: Recreate
  template:
    metadata:
      labels:
        {{- include "openebs-cstor.cvcOperator.labels" . | nindent 8 }}
        {{- if .Values.cvcOperator.podLabels}}
        {{ toYaml .Values.cvcOperator.podLabels | nindent 8 }}
        {{- end}}
    spec:
      serviceAccountName: {{ template "openebs-cstor.serviceAccountName" . }}
      containers:
        - name: {{ template "openebs-cstor.fullname" . }}-cvc-operator
          imagePullPolicy: {{ .Values.cvcOperator.image.pullPolicy }}
          image: "{{ .Values.cvcOperator.image.registry }}{{ .Values.cvcOperator.image.repository }}:{{ .Values.cvcOperator.image.tag }}"
          env:
            # OPENEBS_IO_BASE_DIR is used to configure base directory for openebs on host path.
            # Where OpenEBS can store required files. Default base path will be /var/openebs
            # - name: OPENEBS_IO_BASE_DIR
            #   value: "/var/openebs"
            # OPENEBS_IO_CSTOR_TARGET_DIR can be used to specify the hostpath
            # that to be used for saving the core dump of cstor volume pod.
            # The default path used is /var/openebs/sparse
            #- name: OPENEBS_IO_CSTOR_TARGET_DIR
            #  value: "/var/openebs/sparse"
            - name: OPENEBS_NAMESPACE
              valueFrom:
                fieldRef:
                  fieldPath: metadata.namespace
            - name: OPENEBS_SERVICEACCOUNT_NAME
              valueFrom:
                fieldRef:
                  fieldPath: spec.serviceAccountName
            - name: OPENEBS_IO_CSTOR_TARGET_IMAGE
              value: "{{ .Values.cvcOperator.target.image.registry }}{{ .Values.cvcOperator.target.image.repository }}:{{ .Values.cvcOperator.target.image.tag }}"
            - name:  OPENEBS_IO_CSTOR_VOLUME_MGMT_IMAGE
              value: "{{ .Values.volumeMgmt.target.image.registry }}{{ .Values.volumeMgmt.target.image.repository }}:{{ .Values.volumeMgmt.target.image.tag }}"
            - name:  OPENEBS_IO_VOLUME_MONITOR_IMAGE
              value: "{{ .Values.volumeExporter.target.image.registry }}{{ .Values.volumeExporter.target.image.repository }}:{{ .Values.volumeExporter.target.image.tag }}"
---