kind: StorageClass
apiVersion: storage.k8s.io/v1
metadata:
  name: csi-cstor-stripe
provisioner: cstor.csi.openebs.io
allowVolumeExpansion: true
parameters:
  cas-type: cstor
  replicaCount: "1"
  cstorPoolCluster: cspc-stripe
