name: 'Auto Assign PRs'

# pull_request_target means that this will run on pull requests, but in the context of the base repo.
# This should mean PRs from forks are supported.
on:
  pull_request_target:
    types: [opened, reopened, synchronize, ready_for_review]

jobs:
  add-reviewers:
    runs-on: ubuntu-latest
    steps:
      - uses: kentaro-m/auto-assign-action@v1.1.2
        with:
          configuration-path: ".github/auto_assign.yaml"
          repo-token: "${{ secrets.GITHUB_TOKEN }}"
